### ISSUE TITLE
Logout/Delete account fails

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-ios-client#239]
```python
'NoneType' object has no attribute 'language' (/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/add_1_monkey_patches.py:127)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/277b61042b697c7a_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20180529t134853.410060501450369130/rogerthat/pages/account.py", line 66, in post
    reason = localize(user_profile.language, "Your account has been deleted on your request")
AttributeError: 'NoneType' object has no attribute 'language'
```

**Comment by RubenMattan** [comment]
I know this is a server error, but the user should not be able to delete his account 2 times
